CFLAGS = -c
LIBS = stack.c buffer.c crustache.c
OBJS = $(LIBS:%.c=%.o)

all: libcrustache.a

libcrustache.a:	objs
	rm -f $@
	ar cq $@ $(OBJS)

objs:
	$(CC) $(CFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) libcrustache.a
